framework:
    messenger:
        failure_transport: failed

        transports:

        default_bus: messenger.bus.default

        buses:
            messenger.bus.command: ~
            messenger.bus.query: ~

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\Application\Command\User\CreateUser\CreateUserCommand: async
