<?php

namespace ContainerFG1meaV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sfviqr3Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Sfviqr3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sfviqr3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\UI\\Controller\\GetVehicleController::get' => ['privates', '.service_locator.YB8qYl3.App\\UI\\Controller\\GetVehicleController::get()', 'getGetVehicleControllergetService', true],
            'App\\UI\\Controller\\ListVehiclesByOwnerController::list' => ['privates', '.service_locator.kKBNvNt.App\\UI\\Controller\\ListVehiclesByOwnerController::list()', 'getListVehiclesByOwnerControllerlistService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\UI\\Controller\\GetVehicleController:get' => ['privates', '.service_locator.YB8qYl3.App\\UI\\Controller\\GetVehicleController::get()', 'getGetVehicleControllergetService', true],
            'App\\UI\\Controller\\ListVehiclesByOwnerController:list' => ['privates', '.service_locator.kKBNvNt.App\\UI\\Controller\\ListVehiclesByOwnerController::list()', 'getListVehiclesByOwnerControllerlistService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\UI\\Controller\\GetVehicleController::get' => '?',
            'App\\UI\\Controller\\ListVehiclesByOwnerController::list' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\UI\\Controller\\GetVehicleController:get' => '?',
            'App\\UI\\Controller\\ListVehiclesByOwnerController:list' => '?',
        ]);
    }
}
