<?php

namespace ContainerFG1meaV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineVehicleRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Vehicle\Repository\DoctrineVehicleRepository' shared autowired service.
     *
     * @return \App\Infrastructure\Vehicle\Repository\DoctrineVehicleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Vehicle/Repository/VehicleRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Vehicle/Repository/DoctrineVehicleRepository.php';

        return $container->privates['App\\Infrastructure\\Vehicle\\Repository\\DoctrineVehicleRepository'] = new \App\Infrastructure\Vehicle\Repository\DoctrineVehicleRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
