<?php

namespace ContainerFG1meaV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineUserRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\User\Repository\DoctrineUserRepository' shared autowired service.
     *
     * @return \App\Infrastructure\User\Repository\DoctrineUserRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/User/Repository/UserRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/User/Repository/DoctrineUserRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Infrastructure\\User\\Repository\\DoctrineUserRepository'])) {
            return $container->privates['App\\Infrastructure\\User\\Repository\\DoctrineUserRepository'];
        }

        return $container->privates['App\\Infrastructure\\User\\Repository\\DoctrineUserRepository'] = new \App\Infrastructure\User\Repository\DoctrineUserRepository($a);
    }
}
