<?php

namespace ContainerFG1meaV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListVehiclesByOwnerHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\Handler\Query\Vehicle\ListVehiclesByOwner\ListVehiclesByOwnerHandler' shared autowired service.
     *
     * @return \App\Application\Handler\Query\Vehicle\ListVehiclesByOwner\ListVehiclesByOwnerHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Handler/Query/Vehicle/ListVehiclesByOwner/ListVehiclesByOwnerHandler.php';

        $a = ($container->privates['App\\Infrastructure\\User\\Repository\\DoctrineUserRepository'] ?? $container->load('getDoctrineUserRepositoryService'));

        if (isset($container->privates['App\\Application\\Handler\\Query\\Vehicle\\ListVehiclesByOwner\\ListVehiclesByOwnerHandler'])) {
            return $container->privates['App\\Application\\Handler\\Query\\Vehicle\\ListVehiclesByOwner\\ListVehiclesByOwnerHandler'];
        }

        return $container->privates['App\\Application\\Handler\\Query\\Vehicle\\ListVehiclesByOwner\\ListVehiclesByOwnerHandler'] = new \App\Application\Handler\Query\Vehicle\ListVehiclesByOwner\ListVehiclesByOwnerHandler(($container->privates['App\\Infrastructure\\Vehicle\\Repository\\DoctrineVehicleRepository'] ?? $container->load('getDoctrineVehicleRepositoryService')), $a);
    }
}
