<?php

namespace ContainerOQ8lLXm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListVehiclesByOwnerHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Application\Handler\Query\Vehicle\ListVehiclesByOwner\ListVehiclesByOwnerHandler' shared autowired service.
     *
     * @return \App\Application\Handler\Query\Vehicle\ListVehiclesByOwner\ListVehiclesByOwnerHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/Handler/Query/Vehicle/ListVehiclesByOwner/ListVehiclesByOwnerHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/User/Repository/UserRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/User/Repository/DoctrineUserRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Application\\Handler\\Query\\Vehicle\\ListVehiclesByOwner\\ListVehiclesByOwnerHandler'])) {
            return $container->privates['App\\Application\\Handler\\Query\\Vehicle\\ListVehiclesByOwner\\ListVehiclesByOwnerHandler'];
        }

        return $container->privates['App\\Application\\Handler\\Query\\Vehicle\\ListVehiclesByOwner\\ListVehiclesByOwnerHandler'] = new \App\Application\Handler\Query\Vehicle\ListVehiclesByOwner\ListVehiclesByOwnerHandler(($container->privates['App\\Infrastructure\\Vehicle\\Repository\\DoctrineVehicleRepository'] ?? $container->load('getDoctrineVehicleRepositoryService')), new \App\Infrastructure\User\Repository\DoctrineUserRepository($a));
    }
}
