<?php

namespace ContainerWzMzPr6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListVehiclesByOwnerControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kKBNvNt.App\UI\Controller\ListVehiclesByOwnerController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kKBNvNt.App\\UI\\Controller\\ListVehiclesByOwnerController::list()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'App\\Application\\Handler\\Query\\Vehicle\\ListVehiclesByOwner\\ListVehiclesByOwnerHandler', 'getListVehiclesByOwnerHandlerService', true],
        ], [
            'handler' => 'App\\Application\\Handler\\Query\\Vehicle\\ListVehiclesByOwner\\ListVehiclesByOwnerHandler',
        ]))->withContext('App\\UI\\Controller\\ListVehiclesByOwnerController::list()', $container);
    }
}
