<?php

namespace ContainerWzMzPr6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListVehiclesByOwnerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\UI\Controller\ListVehiclesByOwnerController' shared autowired service.
     *
     * @return \App\UI\Controller\ListVehiclesByOwnerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/UI/Controller/ListVehiclesByOwnerController.php';

        $container->services['App\\UI\\Controller\\ListVehiclesByOwnerController'] = $instance = new \App\UI\Controller\ListVehiclesByOwnerController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\UI\\Controller\\ListVehiclesByOwnerController', $container));

        return $instance;
    }
}
