<?php

namespace Container9MJvX3X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetVehicleControllergetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YB8qYl3.App\UI\Controller\GetVehicleController::get()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YB8qYl3.App\\UI\\Controller\\GetVehicleController::get()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'handler' => ['privates', 'App\\Application\\Handler\\Query\\Vehicle\\GetVehicle\\GetVehicleHandler', 'getGetVehicleHandlerService', true],
        ], [
            'handler' => 'App\\Application\\Handler\\Query\\Vehicle\\GetVehicle\\GetVehicleHandler',
        ]))->withContext('App\\UI\\Controller\\GetVehicleController::get()', $container);
    }
}
