<?php

namespace Container9MJvX3X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetVehicleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\UI\Controller\GetVehicleController' shared autowired service.
     *
     * @return \App\UI\Controller\GetVehicleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/UI/Controller/GetVehicleController.php';

        $container->services['App\\UI\\Controller\\GetVehicleController'] = $instance = new \App\UI\Controller\GetVehicleController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\UI\\Controller\\GetVehicleController', $container));

        return $instance;
    }
}
