<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFG1meaV\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFG1meaV/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFG1meaV.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFG1meaV\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerFG1meaV\App_KernelTestDebugContainer([
    'container.build_hash' => 'FG1meaV',
    'container.build_id' => '685bbdcc',
    'container.build_time' => 1756399579,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFG1meaV');
