<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFupCtZ1\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFupCtZ1/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFupCtZ1.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFupCtZ1\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerFupCtZ1\App_KernelTestDebugContainer([
    'container.build_hash' => 'FupCtZ1',
    'container.build_id' => '3ea44cfb',
    'container.build_time' => 1756313657,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFupCtZ1');
