<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_vehicle_get' => [['id'], ['_controller' => 'App\\UI\\Controller\\GetVehicleController::get'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/vehicles']], [], [], []],
    'api_vehicles_by_owner' => [['ownerId'], ['_controller' => 'App\\UI\\Controller\\ListVehiclesByOwnerController::list'], [], [['text', '/vehicles'], ['variable', '/', '[^/]++', 'ownerId', true], ['text', '/api/owners']], [], [], []],
    'App\UI\Controller\GetVehicleController::get' => [['id'], ['_controller' => 'App\\UI\\Controller\\GetVehicleController::get'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/vehicles']], [], [], []],
    'App\UI\Controller\ListVehiclesByOwnerController::list' => [['ownerId'], ['_controller' => 'App\\UI\\Controller\\ListVehiclesByOwnerController::list'], [], [['text', '/vehicles'], ['variable', '/', '[^/]++', 'ownerId', true], ['text', '/api/owners']], [], [], []],
];
