<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9MJvX3X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9MJvX3X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9MJvX3X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9MJvX3X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9MJvX3X\App_KernelDevDebugContainer([
    'container.build_hash' => '9MJvX3X',
    'container.build_id' => 'c99a45e4',
    'container.build_time' => 1756313382,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9MJvX3X');
