<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDR3Cx9A\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDR3Cx9A/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDR3Cx9A.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDR3Cx9A\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDR3Cx9A\App_KernelDevDebugContainer([
    'container.build_hash' => 'DR3Cx9A',
    'container.build_id' => '17614413',
    'container.build_time' => 1756386526,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDR3Cx9A');
