<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWzMzPr6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWzMzPr6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWzMzPr6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWzMzPr6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWzMzPr6\App_KernelDevDebugContainer([
    'container.build_hash' => 'WzMzPr6',
    'container.build_id' => '44a47c6a',
    'container.build_time' => 1756399486,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWzMzPr6');
